from enum import Enum

from dotenv import load_dotenv
import os

load_dotenv()

BOULEVARD_APP_SECRET_KEY = os.environ.get('BOULEVARD_APP_SECRET_KEY')
BOULEVARD_APP_API_KEY = os.environ.get('BOULEVARD_APP_API_KEY')
BOULEVARD_BUSINESS_ID = os.environ.get('BOULEVARD_BUSINESS_ID')
BOULEVARD_PREFIX = os.environ.get('BOULEVARD_PREFIX')
BOULEVARD_LOCATION_ID = os.environ.get('BOULEVARD_LOCATION_ID')
BOULEVARD_CLIENT_CREATED_WEBHOOK_ID = os.environ.get('BOULEVARD_CLIENT_CREATED_WEBHOOK_ID')

GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = os.environ.get('GOOGLE_SERVICE_ACCOUNT_CREDENTIALS')
REBOOKINGS_SPREADSHEET_ID = os.environ.get('REBOOKINGS_SPREADSHEET_ID')


class SheetHeaderIndex(Enum):
    CLIENT_ID = 0
    CLIENT_NAME = 1
    INITIAL_APPT_BOOKED = 2
    REBOOKED = 3
    INITIAL_APPT_COUNT = 4
    INPUT_TIME = 5
    CLIENT_CREATED_TIME = 6
    ROW_LAST_UPDATED_TIME = 7

